const TOKEN_TYPES = {
    'program': 'palavra-reservada-program',
    'procedure': 'palavra-reservada-procedure',
    'var': 'palavra-reservada-var',
    'begin': 'palavra-reservada-begin',
    'end': 'palavra-reservada-end',
    'if': 'palavra-reservada-if',
    'then': 'palavra-reservada-then',
    'else': 'palavra-reservada-else',
    'while': 'palavra-reservada-while',
    'do': 'palavra-reservada-do',
    '<>': 'operacao-diferente',
    '<': 'operacao-menor',
    '<=': 'operacao-menor-igual',
    '>=': 'operacao-maior-igual',
    '>': 'operacao-maior',
    '+': 'operacao-soma',
    '-': 'operacao-subtracao',
    'or': 'operacao-inclusiva',
    '*': 'operacao-multiplicacao',
    'div': 'operacao-divisao',
    'and': 'operacao-conjuncao',
    'not': 'operacao-negacao',
    'int': 'tipo-inteiro',
    'boolean': 'tipo-boolean',
    'true': 'valor-true',
    'false': 'valor-false',
    ',': 'vírgula',
    ';': 'ponto-vírgula',
    ':': 'dois-pontos',
    '.': 'ponto-final',
    '(': 'abre-parenteses',
    ')': 'fecha-parenteses',
    ':=': 'atribucao',
}

const MAX_LEN = 10
const MAX_INT_LEN = 10